### ISSUE TITLE
metaclass conflict error on Python 2.7.12

### ISSUE THREAD

**Issue by TheProdigyFilippo** [ambv/dj.choices#19]
When running
`from dj.choices import Choices`

exception occurs:

> ...
> return type.__new__(meta, classname, bases, classDict)
> TypeError: Error when calling the metaclass bases
>     metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

It is caused by using `__metaclass__` in line 245 in ` __init__.py`:
```python
class Choices(six.with_metaclass(_ChoicesMeta, list)):                          
    __metaclass__ = _ChoicesMeta
```
Probably `__metaclass__` is not needed when six.with_metaclass is used. Deleting `__metaclass__` fixes the error

**Comment by mkurek** [comment]
Hi @TheProdigyFilippo  - this behaviour has changed in six 1.11.0 (probably because of https://github.com/benjaminp/six/pull/191), so if you want you can freeze six version at 1.10.0 or make PR to dj.choices with removing `__metaclass__` property.

**Comment by konr4d** [comment]
@ambv This is a valid fix. (https://github.com/benjaminp/six/issues/210) Could you please accept the pull request to avoid unnecessary forks?
